pipeline {
    agent any

    tools {
        maven "MAVEN"
        jdk "JDK"
    }

    stages {
        stage('Initialize'){
            steps{
                bat "PATH = ${M2_HOME}/bin:${PATH}"
                bat "M2_HOME = /opt/maven"
            }
        }
        stage('Build') {
    steps {
        dir('my-app') {
            bat 'mvn clean install'
        }
    }
}

     }
    post {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '*/test-reports/.xml'
      )
      }
   } 
}
