pipeline {
    agent any

    tools {
        maven "MAVEN"
        jdk "JDK"
    }

    stages {
        stage('Initialize') {
            steps {
                script {
                    echo "PATH = ${env.PATH}"
                    echo "M2_HOME = ${tool 'MAVEN'}"
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // Detect OS and run the correct command
                    if (isUnix()) {
                        sh 'mvn -B -DskipTests clean package'
                    } else {
                        bat 'mvn -B -DskipTests clean package'
                    }
                }
            }
        }
    }

    post {
        always {
            junit(
                allowEmptyResults: true,
                testResults: '**/test-reports/*.xml'
            )
        }
    }
}

